export const MODAL_ACTIONS = {
    TOGGLE_SHOW_MODAL: 'TOGGLE_SHOW_MODAL',
    CHANGE_M_FIELD: 'CHANGE_M_FIELD',
    CHANGE_N_FIELD: 'CHANGE_N_FIELD',
    CHANGE_X_FIELD: 'CHANGE_X_FIELD',
    SET_ERROR: 'SET_ERROR'
}

export const TABLE_ACTIONS = {
    SET_TABLE_PROPERTIES: 'SET_MATRIX_PROPERTIES',
    ADD_ROW_TO_TABLE: 'ADD_ROW_TO_MATRIX',
    REMOVE_ROW_FROM_TABLE: 'REMOVE_ROW_FROM_MATRIX',
    INCREMENT_CELL: 'INCREMENT_CELL',
    TURN_ON_ROW_PERCENTAGE_VIEW: 'TURN_ON_ROW_PERCENTAGE_VIEW',
    TURN_OF_ROW_PERCENTAGE_VIEW: 'TURN_OF_ROW_PERCENTAGE_VIEW',
    SHOW_COMMON_NUMBERS: 'SHOW_COMMON_NUMBERS'
}

